version: '3.8'

services:
  # Audio Transcriber Service
  audio-transcriber:
    build: ./audio_transcriber
    container_name: umbrella-audio-transcriber
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYANNOTE_TOKEN=${PYANNOTE_TOKEN}
      - REDIS_URL=redis://redis:6379/0
      - SERVICE_NAME=audio-transcriber
    ports:
      - "${AUDIO_TRANSCRIBER_PORT:-8001}:8000"
    volumes:
      - ./audio_transcriber/input:/data/input:ro
      - ./audio_transcriber/output:/data/output
      - whisper-models:/root/.cache/whisper
      - pyannote-models:/root/.cache/torch
    depends_on:
      - redis
    networks:
      - umbrella-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # Future: Document Processor
  # document-processor:
  #   build: ./document_processor
  #   container_name: umbrella-document-processor
  #   ports:
  #     - "${DOCUMENT_PROCESSOR_PORT:-8002}:8000"
  #   depends_on:
  #     - redis
  #   networks:
  #     - umbrella-network

  # Shared Services
  redis:
    image: redis:7-alpine
    container_name: umbrella-redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - umbrella-network

  # API Gateway
  nginx:
    image: nginx:alpine
    container_name: umbrella-gateway
    ports:
      - "${GATEWAY_PORT:-8080}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - audio-transcriber
    networks:
      - umbrella-network

volumes:
  redis-data:
  whisper-models:
  pyannote-models:

networks:
  umbrella-network:
    driver: bridge